### ISSUE TITLE
ratelimit_limit для запросов по API

### ISSUE THREAD

**Issue by AlekseyGur** [RussianInvestments/invest-python#17]
### Описание

​Добрый день.
 
Вижу, что среди пользователей и разработчиков в этом репозитории есть сотрудники банка. Товарищи, прошу вас увеличить ratelimit_limit для запросов по API. Невозможно торговать даже на часовом диапазоне - лимиты слишком низкие. Раз через раз не удаётся выставить заявки и даже стопы к ним.

Вижу, что вы даёте10%  кешбек за сделки, совершённые через API. Так почему тогда ограничиваете их количество лимитом запросов? В чём суть стимулировать людей делать больше сделок и не давать им делать их? В чём состоит стратегия? Я не понимаю.

Напоминаю, что вы можете привязать ratelimit_limit к тарифному плану. Вряд ли кто-то из ваших клиентов решит заддосить миллионом запросов в секунду по самому высокому тарифному плану. Но люди хотя бы не будут испытывать дискомфорт от торговли через API, когда не удаётся выставить стоп лосы из-за ratelimit.

Прошу сделать это уже много лет подряд, много раз. К сожалению, вы не слышыте меня... В итоге, сейчас у самых плохих онлайн игр и соцсетей ограничение на количество действий в минуту выше, чем у банка. И при этом вы пытаетесь давать 10% кешбек за сделки через API. Здесь явно нарушена логика!

С уважением,
Алексей.
​

### Желаемое решение

Надо увеличить ratelimit_limit в 1000 раз. Возможно, привязать это значение к тарифному плану, если уж очень силььно не хочется давать возможность людям делать сделки (вопреки 10% кешбеку за сделки - *тут_нет_логики*)

**Comment by AlekseyGur** [comment]
Пруфы по 10% кешбеку ([ссылка на сайт банка](https://www.tinkoff.ru/invest/open-api/)): 

![изображение](https://github.com/RussianInvestments/invest-python/assets/30201077/6d7ed0e3-fa32-47a2-8ea2-004b169571ad)

Банк говорит: "Делайте как можно больше запросов через API, мы даже деньги наши отдалим вам за это. Но не больше лимита запросов в минуту ratelimit_limit, который у нас ниже чем у любой второсортной онлайн игры."

P.S.
У Тинькова есть несколько проблем, в которых они упёрты как не в себя. Первая - это вот этот ratelimit_limit. Вторая - это отсутствие тёмной темы на сайте, из-за которой инвесторы с деньгами (обычно возраст 60+) сидят перед мониторами в солнцезащитных очках из-за проблем с глазами (мне лично приходится помогать им авторизоваться в банке и перейти в раздел тёмного терминала, где они уже могут самостоятельно работать). Кажется, из-за наличия 10% кешбека руководство банка хоть как-то начало приближаться хотя бы к проблеме с лимитами. Потребуется ещё лет десять, чтобы и тёмную тему на сайт банка прикрутили (которая уже давно есть на промо странице ТиньПремиум)...

**Comment by volkov-invest** [comment]
Добрый день, 
актуальные лимиты - https://russianinvestments.github.io/investAPI/limits/. Лимиты по каждой группе методов свои, т.е. не суммируются. По выставлению ордеров, например, лимит - 300 ордеров в минуту, это по 5 в секунду плюс к этому 200 запросов в минуту на запрос состояний ордеров.

Увеличить лимиты в 1000 раз не можем в силу как инфраструктурных причин и защиты от ddos, так и целесообразности в решаемых задачах, поэтому прошу уточнить:


1) по какому сервису Вам не хватает лимитов? Какие задачи вы не можете решить, так как упираетесь в лимиты? Какое реальное значения лимитов было бы для вас достаточными? 
2) сколько вы в среднем выставляете ордеров в день?

**Comment by volkov-invest** [comment]
Увеличили рейтлимиты по маркетдате вдвое.
