### ISSUE TITLE
Отсутствует trade_type в class TradeInstrument

### ISSUE THREAD

**Issue by andrey-vrn** [RussianInvestments/invest-python#26]
### Что случилось?

Не хватает trade_type в class TradeInstrument по аналогии с order_book_type в OrderBookInstrument.

### Tinkoff Invest Version

0.2.0-beta98

### Python Version

3.11

### OS

Windows

**Comment by andrey-vrn** [comment]
Может, как-то однотипно по аналогии с orderbook сделать?

**Comment by python-invest** [comment]
Будьте добры прикрепить шаги воспроизведения проблемы. 
Модель записана [в соответствии с контрактами](https://github.com/RussianInvestments/invest-python/blob/5836ddce21d8dbbe48a5325f45f0167f4d62db03/protos/tinkoff/invest/grpc/marketdata.proto#L205C4-L208C2)
```
message TradeInstrument {
  string figi = 1 [deprecated = true]; //Deprecated Figi-идентификатор инструмента. Необходимо использовать instrument_id.
  string instrument_id = 2; //Идентификатор инструмента, принимает значение figi или instrument_uid
}
```

**Comment by andrey-vrn** [comment]
Вопрос снят.
