### ISSUE TITLE
Получение процента роста акции

### ISSUE THREAD

**Issue by Borzoff** [RussianInvestments/invest-python#46]
### Что случилось?

Здравствуйте, как получить процент роста акции с начала торгового дня (10:00) до настоящего времени?
Например компании Роснефть (ROSN, Figi - BBG004731354).

### Воспроизведение

```Python
def main():
    with Client(TOKEN) as client:
        from_time = datetime.combine(datetime.today(), datetime.min.time())
        to_time = now()

        print(f"Requesting candles from {from_time} to {to_time} for FIGI {FIGI}")

        candles = client.market_data.get_candles(
            figi=FIGI,
            from_=from_time,
            to=to_time,
            interval=CandleInterval.CANDLE_INTERVAL_1_MIN
        ).candles

        if candles:
            open_price = candles[0].open
            current_price = candles[-1].close
            print(f"Open price: {open_price}")
            print(f"Current price: {current_price}")
        else:
            print("No candles found for today")
            print(f"From: {from_time}, To: {to_time}, FIGI: {FIGI}")


if __name__ == "__main__":
    main()
```

### Tinkoff Invest Version

0.2.0-beta103

### Python Version

3.11

### OS

Windows

### Логи

```Shell
Requesting candles from 2024-07-05 00:00:00 to 2024-07-05 12:12:13.817390+00:00 for FIGI TCS00A0J2Q06
No candles found for today
From: 2024-07-05 00:00:00, To: 2024-07-05 12:12:13.817390+00:00, FIGI: TCS00A0J2Q06
```

**Comment by volkov-invest** [comment]
>Requesting candles from 2024-07-05 00:00:00 to 2024-07-05 12:12:13.817390+00:00 for FIGI **TCS00A0J2Q06**

Судя по логам, у вас в коде поменялся FIGI. Правильный (как вы и написали в начале поста) - **BBG004731354**, а не **TCS00A0J2Q06**



Чтобы решить вашу задачу, можно взять цену открытия из дневной свечи и close из нее же (правда, close может обновляться с небольшими задержками, поэтому если вам нужно в реальном времени - то вместо close используйте цену из GetLastPrice).

Если же хотите рассчитать процент роста на двух минутных свечах - то учитывайте, что для малоликвидных бумаг на некоторых минутах (когда нет сделок) свечи могут быть пустыми.
